Переделана авторизация
praktikumgame/game1 pull request #21
Opened 2020-09-28 08:46 UTC by tohaly

- `React createContext`  заменен на  redux;
- Настроены `devToolsREdux`;
- Переделан HOC  `withAuth`;
- Переделан  `PrivateRouter`;
- Переписаны следующие компоненты:  `Header`, `Signin`, `Signup`, `Settings`;
- Добавлен  HOC `withPreload`;

2020-09-28 11:34 UTC, noveogroup-amorgunov requested changes
/!ok

2020-09-28 11:34 UTC, noveogroup-amorgunov commented on src/redux/auth/actions.ts
> +async function getUserInfo(): Promise<userInfoStateType> {
(!) userInfoStateType тоже название поправить (с большой буквы и постфикс type стоит удалить)

2020-09-28 11:34 UTC, noveogroup-amorgunov commented on src/redux/auth/actions.ts
> +import { initApp } from '../app/actions';
(!) Давай поправим сортировку импортов, сначала внешние, потом относительные из внешних директорий, потом из текущей директории

2020-09-28 11:34 UTC, noveogroup-amorgunov commented on src/redux/auth/helpers.ts
> +  return `${link ? AVATAR_API + link : exampleAvatar}`;
(!) Подожди, метод делает return самой картинки?) Т.е. это будет закодированная строка? Давай передавать ссылку на файл, а не сам файл

2020-09-28 11:34 UTC, noveogroup-amorgunov commented on src/redux/signin/actions.ts
> +      dispatch(signinSuccess());
(?) А если статус не OK, мы все равно пишем, что все хорошо? Кажется это стоит исправить

2020-09-28 11:34 UTC, noveogroup-amorgunov commented on src/redux/signin/reducer.ts
> +      return { ...state, ...{ pending: false } };
можно упросить это код до:

```ts
return { ...state, pending: false };
```

2020-09-28 11:34 UTC, noveogroup-amorgunov commented on src/redux/signup/actions.ts
> +    type: SIGNUP_FATAL,
Я бы FATAL заменил везде на ERROR или FAIL. FATAL - это какая-то фатальная ошибка, а тут просто ошибка)

2020-09-28 11:34 UTC, noveogroup-amorgunov commented on src/redux/signup/actions.ts
> +      dispatch(signinSuccess());
(?) Тот же вопрос, как и в signin

2020-09-28 11:34 UTC, noveogroup-amorgunov commented on src/services/api/helpers/passwordErrorHandler.ts
> +};
(!) Давай сделаем сразу enum-ом общий тип для код-статусов, который можно будет везде использовать

```
enum HTTPCodeStatuses {
  BadRequest = 400,
  NotFount = 404,
  InternalError = 500, 
}
```

ниже statusGlossary нужно вынести из функции (он же статический, незачем при каждом выходе функции генерировать этот объект) и назвать его как-то statusToMessageMap:

```
const statusToMessageMap = {
  [HTTPCodeStatuses.BadRequest]: INCORRECT_OLD_PASSWORD,
  [HTTPCodeStatuses.InternalError]: INITIAL_SERVER_ERROR
}
```

2020-09-29 13:11 UTC, tohaly commented on src/services/auth/helpers/withPreload.tsx
> +const withPreload = <T,>(WrappedComponent: React.ComponentType<T>) => {
Если убрать запятую то ругается, что  JSX тэг не закрыт, я нашел этот хак(с запятой) на просторах интернетов. Да и вопросы по поводу ревью сюда писать или, прямо в гитхабе удобнее?

2020-09-30 13:04 UTC, tohaly commented on src/services/auth/helpers/withAuth.tsx
> +    const newProps = { ...{ isAuthorized: isAuthorized }, ...(props as T) };
Не получается так.

2020-09-30 14:51 UTC, tohaly commented on src/components/Signup/Signup.tsx
> +    clearValues();
В принципе в нашем случае можно обойтись без этой функции, как я понял)

2020-09-30 16:34 UTC, tohaly commented on src/redux/auth/helpers.ts
> +  return `${link ? AVATAR_API + link : exampleAvatar}`;
Хз, если продебажить консолью то выдает линк на картику. Либо я что-то не понял.

2020-09-30 18:26 UTC, noveogroup-amorgunov approved these changes
/ok 🔥

2020-09-30 18:26 UTC, noveogroup-amorgunov commented on src/redux/signin/actions.ts
> +      if (statusMessage === 'OK') {
предлагаю сделать, что если statusMessage не ок, но и исключения не было, то signinError диспатчить, с какой-нибудь ошибкой: "Произошла неизвестная ошибка при авторизации"

2020-09-30 18:26 UTC, noveogroup-amorgunov commented on src/components/Settings/Settings.tsx
> +      dispatch(mismatchPasswords());
(?) Кажется тут опять проблема, если пароли совпали, то диспатчим mismatchPasswords ? Стоит поправить

2020-09-30 18:26 UTC, noveogroup-amorgunov commented on src/redux/auth/helpers.ts
> +  return `${link ? AVATAR_API + link : AVATAR_EXAMPLE_LINK}`;
Все же я рекомендую это поправить. Сейчас картинка попадет в js-бандл, что не ок. Но возможно придется подтюнить конфиг вебпака, чтобы он картинки в dist складывал

2020-09-30 18:35 UTC, Volodya262 approved these changes

2020-09-30 19:09 UTC, tohaly commented on src/redux/auth/reducer.ts
> +  avatar: '',
Я думал у нас будет в хедере приветствие и там будет писаться привет гость))))

2020-10-01 10:17 UTC, merged