Ilya
praktikumgame/game1 pull request #22
Opened 2020-10-07 00:22 UTC by pelyandex

Add reselect to all redux-selectors

2020-10-14 05:54 UTC, pelyandex commented
Разработка движка, карты уровней, анимации спрайтов.
Небольшие фиксы по реакту

2020-10-14 10:52 UTC, noveogroup-amorgunov requested changes
/!ok

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/types/index.tsx
> +export type globalRender = {
(!) Все типы стоит называть с большой буквы GlobalRender.
В данном случае можно назвать GlobalGameState или GlobalGameStateRender

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/types/index.tsx
> +   * Ссылка на скачанное в кеш/оперативную память (я просто хз) изображение
Ссылка на загружённое изображение в память - вполне себе понято

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/sources.tsx
> +export const sprites = ['./images/platfom.png', './images/chelRight.png'];
(!) Лучше сразу сделать именованные спрайты. 

```
sprites = {
  hero: './images/chelRight.png',
  platform: './images/platfom.png'
};
```

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/types/index.tsx
> +    view: {
Если это координаты спрайта, то лучше хранить только индекс/id спрайта, удобнее будет и в коде использовать и для переключения. А сами координаты вынести в отдельный метод для авто получения или словарь и явно захаркодить

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/platforms/types.tsx
> +// }
(!) Весь закоменченный код следует либо удалить, либо поставить TODO с комментом, в какой задаче это будет исправлено

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/platforms/platform.tsx
> +    this.body.coords.view.rY = this.body.coords.y + this.body.images[this.currentImage].frameHeight;
Если сделать деструктизацию const { coords, images } = this.body;  кода станет меньше и он будет читаемее

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/platforms/platform.tsx
> +  accessory = (
Стоит указать комментом, что проверяет метод. Еще лучше, переименовать в название, чтобы по это стало понятно по названию

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/index.tsx
> +  // setTimeout(() => engine.start(), 1000);
(?) Ненужный код?

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/Game.css
> +  height: 380px;
(!) Значения в react компоненте и здесь несовпадают, думаю стоит оставить только в react

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/engine.tsx
> +  globalRender: globalRender = {
gameState по контексту лучше подойдет

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/engine.tsx
> +  initParametrs: InitParametrs;
(?) А почему init? Может просто params?

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/engine.tsx
> +    }
(!) Этот код продублирован ниже для спрайтов, стоит вынести в одно место и переиспользовать

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/engine.tsx
> +        await this.creator(key, obj);
(?) key - это ключ уровня (сейчас есть уровень 1). Но в this.creator обработка есть только для platforms и hero. Что делает метод?

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/engine.tsx
> +    const hero = this.globalRender.hero[0];
const [hero] = this. globalRender.hero;

2020-10-14 10:52 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/engine.tsx
> +  controller(bool: boolean) {
(?) что значит bool ?

2020-10-14 15:08 UTC, pelyandex commented on src/components/Game/scripts/engine.tsx
> +        await this.creator(key, obj);
Это на развитие, когда появятся враги, бонусы и тп

2020-10-14 15:55 UTC, pelyandex commented on debug.log
> +[1007/014601.616:ERROR:directory_reader_win.cc(43)] FindFirstFile: ������� �� ������� ����� ��������� ����. (0x3)
Почему я не могу его найти в репозитории )))) Но в гитигнор кинул.

2020-10-14 16:10 UTC, pelyandex commented on src/components/Game/scripts/engine.tsx
> +  initParametrs: InitParametrs;
По причине того, что нет четкого понимания будущей архитектуры (а когда писалось, и подавно не было). Чтобы чётко понимать, что эти параметры приходят при инициализации игры.

2020-10-14 16:16 UTC, pelyandex commented on src/components/Game/scripts/engine.tsx
> +    }
Из дублирования я нашел только 2 строчки с созданием изображения и вложения в него линка (+ обертка промиса). Для каждого обьекта происходит собственная инициализация, которая заполняет определенные поля, которые в последующем будут задействованы для мат. операций. Смысл данной функции состоит исключительно из загрузки изображения и сохранения его в памяти. Имеет ли смысл выносить его куда-то ? Или я не понимаю о чем речь

2020-10-15 05:41 UTC, noveogroup-amorgunov approved these changes
/ok

2020-10-15 05:41 UTC, noveogroup-amorgunov commented on webpack.config.js
> +  ].filter((el) => typeof el !== 'boolean'),
filter(Boolean) самая короткая запись (тем и удобная), которую используют и в проде. Но это не крит, здесь можно оставить как хочешь

2020-10-15 05:41 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/hero/sourse.ts
> +import { HeroBody } from './types';
(?) Опечатка в названии  файла?  source?

2020-10-15 05:41 UTC, noveogroup-amorgunov commented on src/components/Game/scripts/engine.tsx
> +    }
Вот этот код:

```
          await new Promise((res) => {
            const use = new Image();
            use.src = sprite;
            use.onload = () => res();
          });
```

ниже используется в src/components/Game/scripts/platforms/platform.tsx и в src/components/Game/scripts/hero/hero.tsx

Можно саму загрузку изображений вынести в отдельный хелпер и использовать его как 
```
const images = await loadImages([sprite1, sprite2, ...]);
```

2020-10-19 12:47 UTC, merged